#!/bin/bash

exec 5> debug.txt
BASH_XTRACEFD="5"
PS4='${LINENO}:'
set -x

HOSTS=( "i-x" "i-x" "i-x" "i-x" "i-x" "i-x" )

NAME=( "x" "x" "x"  "x" "x" "xx" )

for HOST in ${!HOSTS[*]} ; do
                aws ec2 create-image --instance-id ${HOSTS[HOST]} --name "${NAME[HOST]}" --description "An AMI for my s
erver ${NAME[$HOST]}" --no-reboot >> amiid
        done

file="amiid"
readarray -t myarray < $file
for NAME in ${!NAMES[*]}; do
 aws ec2 create-tags --resources "${myarray[NAME]}" --tags Key='Name',Value="${NAMES[NAME]}" Key=OCSBusiness,Value="${NAMES[NAME]}"
done
