#!/bin/bash
array=('d1=(i-x i-x i-0ff3c84a9edcc337e)' 'd2=(vol-x vol-x vol-x)')
for elt in "${array[@]}"; do eval $elt; done
        echo " ${d1[@]}  ${d2[@]} "
        aws ec2 create-snapshot --volume-id "${d2[@]}" --description 'Prod backup' --tag-specifications 'ResourceType=snapshot,Tags=[{Key=Name,Value=SafetyCheck},{Key=OCS,Value=Drives}]'

        aws ec2 stop-instances --instance-ids "${d1[@]}"
        aws ec2 modify-instance-attribute --instance-id "${d1[@]}" --instance-type "{\"Value\": \"t2.medium\"}"
        aws ec2 start-instances --instance-ids "${d1[@]}"
~                                                             
