#!/bin/bash
echo "################################################################"
echo "So you have messed your server again"
echo "################################################################"
echo -n "this will setup your website environment with apache(I hope to god that you chose the right set up while you installed your script, this is for CentOS cause Ubuntu is trash"
echo
##info gathering
read -s -p "Enter your wordpress DATABASE password: " PASS
echo
read -s -p "Enter your wordpress DATABASE user: " DUSER
echo 
read -p "Enter your Docker SSH port (for bastion): " PSSH
echo
read -p "Enter your Docker brackets port (for nodejsserver): " PBRA
echo
read -p "Enter your Docker misc port (for nodejsserver): " PRAN
echo
read -p "Do you use Xen server? (this is to install Xen extension: " QXEN
echo
##look I know that last one disapproves the principles of least to know but, I been there

##I am not even going to ask to debug
debugtin(){
	exec 5> debug.txt
	BASH_XTRACEFD="5"
	PS4='${LINENO}:'
	set -x
}
debugtin

read -p "Do you want to setup static networking now?(yes/no): " FQUES

##function to config network
netwokbro(){
if [[ ! -f /etc/sysconfig/network-scripts/ifcfg-eth0 ]]; then
	echo "It looks like the usual ifcfg-eth0 does not exist, please pick the appropriate one and type carefully, I have not cleaned this script yet, so you only have to type it well"
	ls /etc/sysconfig/network-scripts/
	read -p "Select a file: " IPFILE
	while [[ ! -f /etc/sysconfig/network-scripts/$IPFILE ]]; do
		echo "Youu typed shit, pick a file that exists"
		read -p "Select a file: " IPFILE
	done
	cp /etc/sysconfig/network-scripts/$IPFILE /etc/sysconfig/network-scripts/$IPFILE.bak
	echo "this only happens rarely so sorry, just change the BOOTPROTO to none, add your IPADDR GATEWAY DNS1-3 PREFIX ie 16, and god be with you "
	sleep 3
	vi +'se nu' /etc/sysconfig/network-scripts/$IPFILE

else

	NETF=`grep 'BOOTPROTO="dhcp"' /etc/sysconfig/network-scripts/ifcfg-eth0`
	BRUH=/etc/sysconfig/network-scripts/ifcfg-eth0
	if [[ $NETF ]]; then
		cp /etc/sysconfig/network-scripts/ifcfg-eth0 /etc/sysconfig/network-scripts/ifcfg-eth0.bak
		echo IPADDR=$IPADDR >> $BRUH
		echo DNS1="8.8.8.8" >> $BRUH 
		echo DNS2="$GATEWAY" >> $BRUH
		echo DNS3="8.8.4.4" >> $BRUH
		echo GATEWAY="$GATEWAY" >> $BRUH
		echo PREFIX="$PREF" >> $BRUH
		sed -i 's/^BOOTPROTO="dhcp"/BOOTPROTO="static"/' $BRUH
	fi

	test -f /etc/sysconfig/network-scripts/ifcfg-eth0 && cp /etc/sysconfig/network-scripts/ifcfg-eth0 /etc/sysconfig/network-scripts/ifcfg-eth0.bak && sed -i "s/^GATEWAY=.*/GATEWAY=$GATEWAY/;s/^DNS2=.*/DNS2=$GATEWAY/;s/^IPADDR=.*/IPADDR=$IPADDR/" /etc/sysconfig/network-scripts/ifcfg-eth0 || echo "ERROR SOMEWHERE" && sleep 10
	echo "Clean up your /etc/resolv.conf"
	sleep 2
	vi +"se nu" /etc/resolv.conf 
fi

service network restart

}

##if to set up network or nah
if [[ $FQUES =~ ^y|Y(es)$? ]]; then
	read -p "enter your ip: " IPADDR 
	echo
	read -p "enter your gateway: " GATEWAY 
	echo
	read -p "enter your prefix (ie 16): " PREF 
	echo
	netwokbro
fi

##test network
if [[ `ping -c 4 -q 8.8.8.8` ]]; then
	echo "networking fine"
else 
	read -p "enter your ip: " IPADDR 
	echo
	read -p "enter your gateway: " GATEWAY 
	echo
	read -p "enter your prefix (ie 16): " PREF 
	echo
	netwokbro
fi

yum update -y

##test fir xen if the extension is mounted
##might want to take out if not a xen user
xentin(){
CDROMTE=$(blkid /dev/sr0 && echo $?)
if [[ ! $(rpm -qa | grep xe-guest) ]]; then
	while [[ ! $CDROMTE == 0 ]]; do
		echo "mount the agent into cdrom"
	done

	if [[ $CDROMTE == 0 ]]; then
		echo "Trying to mount the agent, I hope you dont have anything in /mnt"
		mount /dev/cdrom /mnt/
		
		if [[ $(echo $?) == 1 ]]; then
			caro=`find /mnt/ -mindepth 1 -type d`
			echo "issues mounting" && if [[ $caro ]]; then mkdir /mnt/xe-gu/; fi && mount -o ro,force /dev/cdrom /mnt/xe-gu/ && bash /mnt/xe-gu/Linux/install.sh -n || echo "Sometin wong" && rm -rf /mnt/xe-gu && mkdir /mnt/xe-gu
		fi
		if [[ -f /mnt/Linux/install.sh ]]; then bash /mnt/Linux/install.sh -n; fi
	fi
fi
}

##test the question I asked before
if [[ $QXEN =~ y|Y(es)$? ]]; then
	xentin
fi

##installs Webserver 
yum grouplist
yum groupinstall "Basic Web Server" -y

##Install Misc
yum install system-config-network docker php httpd ifconfig mariadb-server mariadb git epel-release tmux -y && yum install lsyncd -y
yum --enablerepo=extras install epel-release


##prep the services
service httpd restart
service mariadb restart
service docker restart
service lsyncd restart
chkconfig httpd on
chkconfig docker on
chkconfig mariadb on
chkconfig lsyncd on

##prep docker dirs
mkdir /$USER/dockerstuff && chmod -R 775 /$USER/dockerstuff
mkdir /$USER/websitestuff && chmod -R 775 /$USER/websitestuff

##run docker with the ports specified
docker run  -it -d -p $PSSH:$PSSH --name Bastion ubuntu /bin/bash
#docker exec -ti Bastion /bin/bash -c "apt update ; apt upgrade -y ; apt install ufw -y ; ufw enable ; ufw allow 789789 "

##commnds for docker
NODES="exec 5> $USER/debug.txt ;
BASH_XTRACEFD="5" ;
PS4='${LINENO}:' ;
set -x ;
apt update ; 
apt upgrade -y ; 
apt install vim nano nodejs -y ; 
apt install git npm -y ;
npm install -g brackets ;
ln -s /usr/local/tmp ~/tmp ;
apt install ufw -y ;
ufw enable ;
ufw allow $PBRA ;
service ufw restart ;
ufw reload ;
exit
"

##I would rather sync in isolated than give access
##set firewall
firewall-cmd --zone=public --permanent --add-port=$PSSH/tcp
firewall-cmd --zone=public --permanent --add-port=$PRAN/tcp
firewall-cmd --zone=public --permanent --add-port=$PBRA/tcp
firewall-cmd --zone=public --permanent --add-port=$PBRA/udp
firewall-cmd --zone=public --permanent --add-port=$PSSH/udp
firewall-cmd --zone=public --permanent --add-port=80/tcp
firewall-cmd --zone=public --permanent --add-port=80/udp
firewall-cmd --zone=public --permanent --add-port=443/tcp
firewall-cmd --zone=public --permanent --add-port=443/udp
firewall-cmd --reload

##setup docker brakets nodejs server
docker run --privileged -dit -p $PRAN:$PRAN -p $PBRA:$PBRA -v /$USER/websitestuff:/var/www --name nodejsserver ubuntu  
docker exec -ti nodejsserver /bin/bash -c  "$NODES"
docker exec -ti nodejsserver /bin/bash -c  "brackets --port $PBRA --proj-dir /$USER/websitestuff --supp-dir ~/my-project/ " &
#docker exec -ti nodejsserver /bin/bash -c  "echo 'brackets --port $PBRA --proj-dir /$USER/websitestuff --supp-dir ~/my-project/ &' >> /etc/rc.local" 
#docker inspect --format="{{.Id}}" namebrac
echo "committing the containers into the hand of the lord"
docker commit nodejsserver
docker commit Bastion
#echo "alias nodejsserver=\"docker exec -ti nodejsserver /bin/bash -c  \"brackets --port $PBRA --proj-dir /$USER/websitestuff --supp-dir ~/my-project/ \" &" >> ~/.bashrc

##add docker to startup
echo "docker start Bastion" >> /etc/rc.local
#echo "docker start nodejsserver" >> /etc/rc.local

##deamonize the dirs neccessary
lsyncd -rsync /root/websitestuff/ /var/www/html/ -insist -delay 0
echo "lsyncd -rsync /root/websitestuff/ /var/www/html/ -insist -delay 0" >> /etc/rc.local

##setup wordpress database
mysql -u root -e "CREATE DATABASE wordpress"
mysql -u root -e "CREATE USER $USER@localhost IDENTIFIED BY $PASS"
mysql -u root -e "GRANT ALL PRIVILEGES ON wordpress.* TO $USER@localhost IDENTIFIED BY $PASS"
mysql -u root -e "FLUSH PRIVILEGES"

yum install php-gd -y

mkdir /var/www/html/wordpress && wget http://wordpress.org/latest.tar.gz
tar -xzvf latest.tar.gz -C /var/www/html/ && find -name ^late*gz$ -delete
chown -R apache:apache /var/www/html/*

cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php

sed -i "s/^define('DB_NAME', 'database_name_here')/define('DB_NAME', '$DUSER')/ ; s/^define('DB_USER', 'username_here')/define('DB_USER', '$USER')/ ; s/^define('DB_PASSWORD', 'password_here')/define('DB_PASSWORD', '$PASS')/ " /var/www/html/wordpress/wp-config.php

##Additions to install Powershell
##powershell

while true; do
	echo
	echo "Additional unneccessary fancy stuff"
	echo "1) installs powershell"
	echo "2) installs vagrant "
	echo "3) installs byobu"
	echo "4) installs AWSCLI"
	echo "5) installs openstack lol ok"
	echo "b) bye"
	echo
	read WATSITGONBE

	case $WATSITGONBE in
		1)	echo "installing powershell"
			curl https://packages.microsoft.com/config/rhel/7/prod.repo | sudo tee /etc/yum.repos.d/microsoft.repo

			if [[ -d ~/powershell ]]; then mkdir ~/powershell && cd ~/powershell; fi
			yum install -y powershell && echo "alias pwsh=powershell" >> ~/.bash_profile
			source ~/.bash_profile
			;;
		2)	echo "installing vagrant"
			yum -y install gcc dkms make qt libgomp patch 
			yum -y install kernel-headers kernel-devel binutils glibc-headers glibc-devel font-forge
			cd /etc/yum.repo.d/ && wget http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo
			yum install -y VirtualBox-5.1
			/sbin/rcvboxdrv setup
			yum -y install https://releases.hashicorp.com/vagrant/1.9.6/vagrant_1.9.6_x86_64.rpm
			mkdir ~/vagrant-home && cd ~/vagrant-home
			echo "Vagrant instructions 
				# vagrant halt     [shutdown server]
				# vagrant up       [start server]
				# vagrant destroy  [delete server]"
			sleep 4
			echo -n "Do you want to install ubuntu? or Do you want to install centOS? Anse"
			read -r YESUC
			if [[ $YESUC =~ ^c|C(entos)?$ ]]; then
				vagrant init ubuntu/xenial164
			elif [[ $YESUC =~ ^u|U(buntu)?$ ]]; then
				vagrant init centos/7
			fi
			;;
		3) echo "installing byobu"
			yum install byobu -y
			;;
		4) echo "installing AWSCLI"
		awstin(){
		if [[ ! $(which python) ]]; then yum install python -y; fi
		echo "your python version: $(python --version)"
		if [[ ! -d ~/pip ]]; then mkdir ~/pip && cd ~/pip && curl -O https://bootstrap.pypa.io/get-pip.py; else cd ~/pip && curl -O https://bootstrap.pypa.io/get-pip.py; fi && python ~/pip/get-pip.py --user && export PATH=~/.local/bin:$PATH && echo "export PATH=~/.local/bin:$PATH" >> ~/.bash_profile
		pip --version
		echo "your python verion: $(pip --version)"
		pip install awscli --upgrade --user
		echo "your python verion: $(aws --version)"
		}
		echo -n "Do you want an isolated AWSCLI env or nah, note; if yes we will run this a docker environment keeping your keys safe if you get compromized, not convinient however because you would have to do your volume mountings and whatnot, if no then we just install AWSCLI on your host machine and you just have to keep it safe. The goal is to protect your AWS pragmatic or whateva access keys"
		echo -n "yes for (install in isolated env:docker) no or wrong anwser for (just install anywhere fam u stressin)"
		sleep 3
		echo
		read -r ANZ
		if [[ $ANZ =~ ^y(es)?$ ]]; then
			docker run --privileged -dit -v /$USER/dockerstuff:/$USER --name awscli centos
			lol=`type awstin | sed '1d;2d;3d;$d;s/--user//;s/pip install awscli --upgrade .*/pip install awscli --upgrade --ignore-installed six/'`
			docker exec -ti awscli /bin/bash -c  "$lol"
			docker commit awscli
			echo "docker start awscli" >> /etc/rc.local
		else	
			yum install python-setuptools
			awstin
			if [[ ! `type aws` ]]; then pip install awscli --upgrade --user; fi
		fi
		echo "Make sure to get your keys, configure aws with aws configure"
		;;
	5) echo "Bruh are you sure, this will consume alot of resources"
	##comin soon, least of priorities
		;;
	b) 
		echo "See ya"
		break
		;;

    *)	echo "scuuz me ?"
		;;	
	esac
done
echo










