#!/bin/bash
yum update -y
yum install mdadm lvm2 nfs-utils samba samba-client samba-common firewalld -y
mkdir -p /srv/nfsshare
chmod -R 755 /srv/nfsshare
chown nfsnobody:nfsnobody /srv/nfsshare
systemctl start firewalld
systemctl enable firewalld
systemctl status firewalld
systemctl enable rpcbind
systemctl enable nfs-server
systemctl enable nfs-lock
systemctl enable nfs-idmap
systemctl start rpcbind
systemctl start nfs-server
systemctl start nfs-lock
systemctl start nfs-idmap
echo "/srv/nfsshare   *(rw,sync,no_root_squash,no_all_squash)"  >> /etc/exports
systemctl restart nfs-server
service firewalld restart
firewall-cmd --permanent --zone=public --add-service=nfs
firewall-cmd --permanent --zone=public --add-service=mountd
firewall-cmd --permanent --zone=public --add-service=rpc-bind
firewall-cmd --permanent --zone=public --add-service=samba
firewall-cmd --reload
cp /etc/samba/smb.conf /etc/samba/smb.conf.orig
parted --script /dev/md0 \
    mklabel gpt \
    mkpart primary 1 90% \
    name 1 RaidVol \
    set 1 lvm on
pvcreate /dev/md0p1
vgcreate VGRaidVol /dev/md0p1
lvcreate -n LVRaid -l 100%FREE VGRaidVol
 mkfs.xfs -L RaidXFSVol /dev/mapper/VGRaidVol-LVRaid
mount -L RaidXFSVol /srv/ || exit
echo "LABEL=RaidXFSVol /srv           xfs     rw,suid,exec,auto,nouser,async,_netdev,acl      0 0" >> /etc/fstab




